apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ekkumarlinux/wordpress-mini
    targetRevision: HEAD
    path: wordpress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
